# site settings
title: My Portfolio
subtitle: Lindsey Smith
email: lindseysmith1580@gmail.com
description: I'm a detail-oriented and efficient software developer with a focus on building practical, user-centered applications. I’m experienced in JavaScript, React, Java, Spring Boot, and SQL. I value authenticity, hard work, and clear communication, and I’m passionate about continuous learning and solving meaningful problems through technology. I’m currently seeking opportunities where I can grow as a developer, contribute to impactful projects, and collaborate with teams that prioritize innovation and user experience.
baseurl: "/home" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/lsmith1580
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/lindsey-rene-smith/
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
